services:
  db:
    image: mysql:8.0
    container_name: vitalis_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_pwd
      MYSQL_DATABASE: vitalis_db
      MYSQL_USER: vitalis_user
      MYSQL_PASSWORD: vitalis_pwd
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
volumes:
  mysql_data:
